# This is a basic workflow to help you get started with Actions
name: 'Security Scan'
on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Snyk Scanning
          uses: nn-dma/security_check@main
          with:
            SnykToken: ${{ secrets.SNYK_TOKEN }}
            Pipeline_Run: ${{ github.run_id }}


    
    