# This is a basic workflow to help you get started with Actions
name: 'Security Scan'
on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Check for install files
          uses: nn-dma/check_for_custom_install_scripts@main
          with:
            install_script_path: 'scripts/install'


    
    